@php($rtl = app()->getLocale() === 'ar')
<!doctype html><html lang="{{ app()->getLocale() }}" dir="{{ $rtl ? 'rtl' : 'ltr' }}"><head><meta charset="utf-8"><style>body{font-family:DejaVu Sans,sans-serif;direction:{{ $rtl ? 'rtl' : 'ltr' }};font-size:11px;color:#111827;margin:28px}h1{font-size:22px}h2{font-size:15px;border-bottom:1px solid #d1d5db;padding-bottom:5px;margin-top:22px}table{width:100%;border-collapse:collapse;margin-top:8px}th,td{border:1px solid #d1d5db;padding:6px;text-align:{{ $rtl ? 'right' : 'left' }}}th{background:#f3f4f6}.cover{text-align:center;padding:20px;border:1px solid #d1d5db}.logo{max-height:72px;max-width:180px}.muted{color:#6b7280}.danger{color:#b91c1c}.warning{color:#b45309}</style></head><body>
<section class="cover">@if($institution->institution_logo)<img class="logo" src="{{ $institution->institution_logo }}" alt=""><br>@endif<h1>{{ $institution->institution_name }}</h1><p>{{ __('monitoring.executive.report.system_name') }}</p><h2>{{ __('monitoring.executive.report.title') }}</h2><p class="muted">{{ $periodStart->translatedFormat('F Y') }}</p></section>
<h2>{{ __('monitoring.pdf_reports.executive_summary') }}</h2><p>{{ $summaryText }}</p>
<h2>{{ __('monitoring.executive.sections.sla') }}</h2><table><tr><th>{{ __('monitoring.executive.sla.weighted_availability') }}</th><th>{{ __('monitoring.executive.cards.sla_met') }}</th><th>{{ __('monitoring.executive.cards.sla_at_risk') }}</th><th>{{ __('monitoring.executive.cards.sla_breached') }}</th></tr><tr><td>{{ $dashboard['sla']['weighted_availability'] === null ? '-' : number_format($dashboard['sla']['weighted_availability'], 2).'%' }}</td><td>{{ $dashboard['sla']['met'] }}</td><td>{{ $dashboard['sla']['at_risk'] }}</td><td>{{ $dashboard['sla']['breached'] }}</td></tr></table>
<h2>{{ __('monitoring.executive.sections.incidents') }}</h2><table><tr><th>{{ __('monitoring.executive.cards.open_incidents') }}</th><th>{{ __('monitoring.executive.incidents.downtime') }}</th><th>{{ __('monitoring.executive.incidents.most_affected') }}</th></tr><tr><td>{{ $dashboard['counts']['open_incidents'] }}</td><td>{{ gmdate('H:i:s', $dashboard['incidents']['downtime_seconds']) }}</td><td>{{ $dashboard['incidents']['most_affected'] ?? '-' }}</td></tr></table>
<h2>{{ __('monitoring.executive.sections.ssl') }}</h2><p>≤ 30: {{ $dashboard['ssl']['within_30'] }} &nbsp; ≤ 14: {{ $dashboard['ssl']['within_14'] }} &nbsp; ≤ 7: {{ $dashboard['ssl']['within_7'] }}</p>
<h2>{{ __('monitoring.executive.sections.spc') }}</h2><p>{{ __('monitoring.executive.spc.points', ['count' => $dashboard['spc']['points']]) }}</p>
<h2>{{ __('monitoring.executive.report.previous_period') }}</h2>@if($previous)<p>{{ __('monitoring.executive.sla.weighted_availability') }}: {{ $previous['sla']['weighted_availability'] === null ? '-' : number_format($previous['sla']['weighted_availability'], 2).'%' }} → {{ $dashboard['sla']['weighted_availability'] === null ? '-' : number_format($dashboard['sla']['weighted_availability'], 2).'%' }}</p>@else<p>{{ __('monitoring.executive.report.no_previous') }}</p>@endif
<h2>{{ __('monitoring.interpretation.sections.key_findings_and_recommendations') }}</h2><ul>@foreach($recommendations as $recommendation)<li>{{ $recommendation }}</li>@endforeach</ul>
</body></html>
